version: "3"

services:
    nacho:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: imageify
        ports:
            - 88:80
        volumes:
            - ./:/var/www/html

volumes:
    datavolume:
        external: false